### ISSUE TITLE
大佬，请问你这个tensorRT只做特征提取部分是什么意思？onnx模型加载进来如何截取只对特征提取部分进行tensorRT加速？

### ISSUE THREAD

**Issue by shining-love** [GesilaA/deepsort_tensorrt#1]

**Comment by GesilaA** [comment]
就是这个是用TensorRT来进行网络前传的，按照demo进行传参就可以了。现在这个有些乱，有时间我会整理好后重新上传一份

**Comment by shining-love** [comment]
> 就是这个是用TensorRT来进行网络前传的，按照demo进行传参就可以了。现在这个有些乱，有时间我会整理好后重新上传一份

我已經理解了。只对特征部分做提取。是从onnx导出时就截断了
