### ISSUE TITLE
我在win10下编译的时候报错

### ISSUE THREAD

**Issue by lbq779660843** [GesilaA/deepsort_tensorrt#12]
你好，我自己改了Cmakelist以适配win10的环境，但在vs2019下生成(make)的时候报错，
**LNK1181 无法打开输入文件“Release\deepsort.lib”**, 
我打开对应的文件夹，发现下面只有一个deepsort.dll文件。

**Comment by GesilaA** [comment]
windows连接动态库需要有lib文件，试试直接把cmakelist里面的SHARED改为STATIC，全部使用静态库

**Comment by lbq779660843** [comment]
谢谢，成功了，如果有需要我在这里可以在这里分享我的Cmakelist

**Comment by GesilaA** [comment]
可以哦，谢谢你

**Comment by lbq779660843** [comment]
你好，运行demo测试的时候出现了下面的问题，我看了tensorrtx他们讨论的，是不是要改某处？
#https://github.com/wang-xinyu/tensorrtx/issues/25

![捕获](https://user-images.githubusercontent.com/27773249/134313280-3939587c-dd9c-4c53-a02b-d80cdc8413d2.JPG)

**Comment by Bian-666** [comment]
> 你好，运行demo测试的时候出现了下面的问题，我看了tensorrtx他们讨论的，是不是要改某处？ #[wang-xinyu/tensorrtx#25](https://github.com/wang-xinyu/tensorrtx/issues/25)
> 
> ![捕获](https://user-images.githubusercontent.com/27773249/134313280-3939587c-dd9c-4c53-a02b-d80cdc8413d2.JPG)

你好，找到原因了吗
