### ISSUE TITLE
TRT ERROR

### ISSUE THREAD

**Issue by PeppermintSummer** [GesilaA/deepsort_tensorrt#5]
当我在 Windows 10 中运行这个demo时，我遇到了这个错误！为什么会反序列化失败？
![image](https://user-images.githubusercontent.com/44369655/122881819-270da100-d36e-11eb-9b64-7989835825ab.png)

**Comment by GesilaA** [comment]
在assert(builder != nullptr)处出错了，检查一下tensorrt7是不是已经正确安装了<br>
![Selection_017](https://user-images.githubusercontent.com/19608156/122890890-ab642200-d376-11eb-87fe-a9c5b05a94dc.png)

**Comment by PeppermintSummer** [comment]
嗯，windows读写文件要添加ios::binary。只是又报了个很奇怪的错，==
![image](https://user-images.githubusercontent.com/44369655/122894329-ac4a8300-d379-11eb-8dac-3185b99446fe.png)

**Comment by PeppermintSummer** [comment]
已解决！感谢
